### ISSUE TITLE
Is this working with Rails 4 and Mongoid 4.0.0beta1?

### ISSUE THREAD

**Issue by abitdodgy** [frodsan/mongoid-minitest#19]
I'm getting this error when I try to run my test. Any idea why?

````
Mohamads-MacBook-Pro:wc Mohamad$ rake test test/models/user_test.rb
rake aborted!
NameError: uninitialized constant Mongoid::Paranoia
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/matchers/document/document.rb:5:in `<module:Document>'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/matchers/document/document.rb:3:in `<module:Matchers>'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/matchers/document/document.rb:2:in `<module:Mongoid>'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/matchers/document/document.rb:1:in `<top (required)>'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/mongoid-minitest.rb:3:in `require'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mongoid-minitest-506409616bdd/lib/mongoid-minitest.rb:3:in `<top (required)>'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/Users/Mohamad/Documents/Code/wc/config/application.rb:12:in `<top (required)>'
/Users/Mohamad/Documents/Code/wc/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Mohamads-MacBook-Pro:wc Mohamad$ 
````

Here's my `Gemfile`:

````ruby
gem 'rails', '4.0.2'

gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'
gem 'bson_ext'

group :test do
  gem 'mongoid-minitest', github: 'frodsan/mongoid-minitest'
end
````

Here's my `test_helper`:

````ruby
ENV["RAILS_ENV"] ||= "test"
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

require 'minitest/autorun'
require 'mongoid'
require 'mongoid-minitest'

class ActiveSupport::TestCase
  # Add more helper methods to be used by all tests here...
end
````

And here is my test:

require 'test_helper'

````ruby
class UserTest < ActiveSupport::TestCase
  test "true is true" do
    assert true
  end
end
````

Finally, my `user.rb` model:

````ruby
class User
  include Mongoid::Document
end
````

**Comment by rmm5t** [comment]
More to come to get the build matrix fully green, but this should be fixed by 4064b42aea2116a2b8128f5e0905244e11ea17c7 and 03351d9f06072a64c34d9949b10025bd0de1592c
