### ISSUE TITLE
LoadError: cannot load such file -- minitest/matchers

### ISSUE THREAD

**Issue by bgvo** [frodsan/mongoid-minitest#21]
Hi!

Running `bundle exec rake test` brings me:

```
rake aborted!
LoadError: cannot load such file -- minitest/matchers
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/config/application.rb:14:in `<top (required)>'
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/Rakefile:4:in `require'
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- minitest/matchers_vaccine
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/config/application.rb:14:in `<top (required)>'
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/Rakefile:4:in `require'
/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

My Gemfile:

```
...
group :test do
	gem 'mongoid-minitest'
	gem "factory_girl_rails"
	gem "capybara"
	gem 'faker'
end
```

Any idea on what can I do to fix it? 

Thanks.

**Comment by rmm5t** [comment]
The latest version allows you to choose between minitest-matchers or
minitest-matchers_vaccine, but doesn't depend on either directly, so you
now have to do that yourself.

Add minitest-matchers to the test group of your Gemfile.

Probably worthy of a readme update explaining this.

**Comment by bgvo** [comment]
Thanks a lot. It worked.
